// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed.proto

package feed

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tag struct {
	TagKey               string   `protobuf:"bytes,1,opt,name=tag_key,json=tagKey,proto3" json:"tag_key,omitempty"`
	TagLink              string   `protobuf:"bytes,2,opt,name=tag_link,json=tagLink,proto3" json:"tag_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{0}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagKey() string {
	if m != nil {
		return m.TagKey
	}
	return ""
}

func (m *Tag) GetTagLink() string {
	if m != nil {
		return m.TagLink
	}
	return ""
}

type Tags struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Props                *TagsCardProps `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Tags) Reset()         { *m = Tags{} }
func (m *Tags) String() string { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()    {}
func (*Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{1}
}

func (m *Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags.Unmarshal(m, b)
}
func (m *Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags.Marshal(b, m, deterministic)
}
func (m *Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags.Merge(m, src)
}
func (m *Tags) XXX_Size() int {
	return xxx_messageInfo_Tags.Size(m)
}
func (m *Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Tags proto.InternalMessageInfo

func (m *Tags) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Tags) GetProps() *TagsCardProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type TagsCardProps struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TagsArray            []*Tag   `protobuf:"bytes,2,rep,name=tags_array,json=tagsArray,proto3" json:"tags_array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagsCardProps) Reset()         { *m = TagsCardProps{} }
func (m *TagsCardProps) String() string { return proto.CompactTextString(m) }
func (*TagsCardProps) ProtoMessage()    {}
func (*TagsCardProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{2}
}

func (m *TagsCardProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagsCardProps.Unmarshal(m, b)
}
func (m *TagsCardProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagsCardProps.Marshal(b, m, deterministic)
}
func (m *TagsCardProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagsCardProps.Merge(m, src)
}
func (m *TagsCardProps) XXX_Size() int {
	return xxx_messageInfo_TagsCardProps.Size(m)
}
func (m *TagsCardProps) XXX_DiscardUnknown() {
	xxx_messageInfo_TagsCardProps.DiscardUnknown(m)
}

var xxx_messageInfo_TagsCardProps proto.InternalMessageInfo

func (m *TagsCardProps) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TagsCardProps) GetTagsArray() []*Tag {
	if m != nil {
		return m.TagsArray
	}
	return nil
}

type VideoList struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Props                *VideoListProps `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VideoList) Reset()         { *m = VideoList{} }
func (m *VideoList) String() string { return proto.CompactTextString(m) }
func (*VideoList) ProtoMessage()    {}
func (*VideoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{3}
}

func (m *VideoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoList.Unmarshal(m, b)
}
func (m *VideoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoList.Marshal(b, m, deterministic)
}
func (m *VideoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoList.Merge(m, src)
}
func (m *VideoList) XXX_Size() int {
	return xxx_messageInfo_VideoList.Size(m)
}
func (m *VideoList) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoList.DiscardUnknown(m)
}

var xxx_messageInfo_VideoList proto.InternalMessageInfo

func (m *VideoList) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VideoList) GetProps() *VideoListProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type VideoListProps struct {
	Title                string                       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Alignment            string                       `protobuf:"bytes,2,opt,name=alignment,proto3" json:"alignment,omitempty"`
	SeeAll               string                       `protobuf:"bytes,3,opt,name=see_all,json=seeAll,proto3" json:"see_all,omitempty"`
	VideoArray           []*VideoListPropsArrayObject `protobuf:"bytes,4,rep,name=videoArray,proto3" json:"videoArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *VideoListProps) Reset()         { *m = VideoListProps{} }
func (m *VideoListProps) String() string { return proto.CompactTextString(m) }
func (*VideoListProps) ProtoMessage()    {}
func (*VideoListProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{4}
}

func (m *VideoListProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoListProps.Unmarshal(m, b)
}
func (m *VideoListProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoListProps.Marshal(b, m, deterministic)
}
func (m *VideoListProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoListProps.Merge(m, src)
}
func (m *VideoListProps) XXX_Size() int {
	return xxx_messageInfo_VideoListProps.Size(m)
}
func (m *VideoListProps) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoListProps.DiscardUnknown(m)
}

var xxx_messageInfo_VideoListProps proto.InternalMessageInfo

func (m *VideoListProps) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoListProps) GetAlignment() string {
	if m != nil {
		return m.Alignment
	}
	return ""
}

func (m *VideoListProps) GetSeeAll() string {
	if m != nil {
		return m.SeeAll
	}
	return ""
}

func (m *VideoListProps) GetVideoArray() []*VideoListPropsArrayObject {
	if m != nil {
		return m.VideoArray
	}
	return nil
}

type VideoListPropsArrayObject struct {
	VideoLink            string   `protobuf:"bytes,1,opt,name=video_link,json=videoLink,proto3" json:"video_link,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	ShopLook             string   `protobuf:"bytes,3,opt,name=shop_look,json=shopLook,proto3" json:"shop_look,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoListPropsArrayObject) Reset()         { *m = VideoListPropsArrayObject{} }
func (m *VideoListPropsArrayObject) String() string { return proto.CompactTextString(m) }
func (*VideoListPropsArrayObject) ProtoMessage()    {}
func (*VideoListPropsArrayObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{5}
}

func (m *VideoListPropsArrayObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoListPropsArrayObject.Unmarshal(m, b)
}
func (m *VideoListPropsArrayObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoListPropsArrayObject.Marshal(b, m, deterministic)
}
func (m *VideoListPropsArrayObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoListPropsArrayObject.Merge(m, src)
}
func (m *VideoListPropsArrayObject) XXX_Size() int {
	return xxx_messageInfo_VideoListPropsArrayObject.Size(m)
}
func (m *VideoListPropsArrayObject) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoListPropsArrayObject.DiscardUnknown(m)
}

var xxx_messageInfo_VideoListPropsArrayObject proto.InternalMessageInfo

func (m *VideoListPropsArrayObject) GetVideoLink() string {
	if m != nil {
		return m.VideoLink
	}
	return ""
}

func (m *VideoListPropsArrayObject) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VideoListPropsArrayObject) GetShopLook() string {
	if m != nil {
		return m.ShopLook
	}
	return ""
}

type ShopList struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Props                *ShopListProps `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShopList) Reset()         { *m = ShopList{} }
func (m *ShopList) String() string { return proto.CompactTextString(m) }
func (*ShopList) ProtoMessage()    {}
func (*ShopList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{6}
}

func (m *ShopList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopList.Unmarshal(m, b)
}
func (m *ShopList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopList.Marshal(b, m, deterministic)
}
func (m *ShopList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopList.Merge(m, src)
}
func (m *ShopList) XXX_Size() int {
	return xxx_messageInfo_ShopList.Size(m)
}
func (m *ShopList) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopList.DiscardUnknown(m)
}

var xxx_messageInfo_ShopList proto.InternalMessageInfo

func (m *ShopList) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ShopList) GetProps() *ShopListProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type ShopListProps struct {
	Title                string                      `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Alignment            string                      `protobuf:"bytes,2,opt,name=alignment,proto3" json:"alignment,omitempty"`
	SeeAll               string                      `protobuf:"bytes,3,opt,name=see_all,json=seeAll,proto3" json:"see_all,omitempty"`
	ShopArray            []*ShopListPropsArrayObject `protobuf:"bytes,4,rep,name=shop_array,json=shopArray,proto3" json:"shop_array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ShopListProps) Reset()         { *m = ShopListProps{} }
func (m *ShopListProps) String() string { return proto.CompactTextString(m) }
func (*ShopListProps) ProtoMessage()    {}
func (*ShopListProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{7}
}

func (m *ShopListProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopListProps.Unmarshal(m, b)
}
func (m *ShopListProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopListProps.Marshal(b, m, deterministic)
}
func (m *ShopListProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopListProps.Merge(m, src)
}
func (m *ShopListProps) XXX_Size() int {
	return xxx_messageInfo_ShopListProps.Size(m)
}
func (m *ShopListProps) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopListProps.DiscardUnknown(m)
}

var xxx_messageInfo_ShopListProps proto.InternalMessageInfo

func (m *ShopListProps) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ShopListProps) GetAlignment() string {
	if m != nil {
		return m.Alignment
	}
	return ""
}

func (m *ShopListProps) GetSeeAll() string {
	if m != nil {
		return m.SeeAll
	}
	return ""
}

func (m *ShopListProps) GetShopArray() []*ShopListPropsArrayObject {
	if m != nil {
		return m.ShopArray
	}
	return nil
}

type ShopListPropsArrayObject struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	SubTitle             string   `protobuf:"bytes,2,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopListPropsArrayObject) Reset()         { *m = ShopListPropsArrayObject{} }
func (m *ShopListPropsArrayObject) String() string { return proto.CompactTextString(m) }
func (*ShopListPropsArrayObject) ProtoMessage()    {}
func (*ShopListPropsArrayObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{8}
}

func (m *ShopListPropsArrayObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopListPropsArrayObject.Unmarshal(m, b)
}
func (m *ShopListPropsArrayObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopListPropsArrayObject.Marshal(b, m, deterministic)
}
func (m *ShopListPropsArrayObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopListPropsArrayObject.Merge(m, src)
}
func (m *ShopListPropsArrayObject) XXX_Size() int {
	return xxx_messageInfo_ShopListPropsArrayObject.Size(m)
}
func (m *ShopListPropsArrayObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopListPropsArrayObject.DiscardUnknown(m)
}

var xxx_messageInfo_ShopListPropsArrayObject proto.InternalMessageInfo

func (m *ShopListPropsArrayObject) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ShopListPropsArrayObject) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *ShopListPropsArrayObject) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListPage struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Props                *ListPageProps `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPage) Reset()         { *m = ListPage{} }
func (m *ListPage) String() string { return proto.CompactTextString(m) }
func (*ListPage) ProtoMessage()    {}
func (*ListPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{9}
}

func (m *ListPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPage.Unmarshal(m, b)
}
func (m *ListPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPage.Marshal(b, m, deterministic)
}
func (m *ListPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPage.Merge(m, src)
}
func (m *ListPage) XXX_Size() int {
	return xxx_messageInfo_ListPage.Size(m)
}
func (m *ListPage) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPage.DiscardUnknown(m)
}

var xxx_messageInfo_ListPage proto.InternalMessageInfo

func (m *ListPage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ListPage) GetProps() *ListPageProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type ListPageProps struct {
	ListArray            []*ListPagePropsArrayObject `protobuf:"bytes,1,rep,name=listArray,proto3" json:"listArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListPageProps) Reset()         { *m = ListPageProps{} }
func (m *ListPageProps) String() string { return proto.CompactTextString(m) }
func (*ListPageProps) ProtoMessage()    {}
func (*ListPageProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{10}
}

func (m *ListPageProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPageProps.Unmarshal(m, b)
}
func (m *ListPageProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPageProps.Marshal(b, m, deterministic)
}
func (m *ListPageProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPageProps.Merge(m, src)
}
func (m *ListPageProps) XXX_Size() int {
	return xxx_messageInfo_ListPageProps.Size(m)
}
func (m *ListPageProps) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPageProps.DiscardUnknown(m)
}

var xxx_messageInfo_ListPageProps proto.InternalMessageInfo

func (m *ListPageProps) GetListArray() []*ListPagePropsArrayObject {
	if m != nil {
		return m.ListArray
	}
	return nil
}

type ListPagePropsArrayObject struct {
	CelebImage           string   `protobuf:"bytes,1,opt,name=celeb_image,json=celebImage,proto3" json:"celeb_image,omitempty"`
	StyleImage           string   `protobuf:"bytes,2,opt,name=style_image,json=styleImage,proto3" json:"style_image,omitempty"`
	SubTitle             string   `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Mrp                  int64    `protobuf:"varint,4,opt,name=mrp,proto3" json:"mrp,omitempty"`
	DiscountPrice        int64    `protobuf:"varint,5,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPagePropsArrayObject) Reset()         { *m = ListPagePropsArrayObject{} }
func (m *ListPagePropsArrayObject) String() string { return proto.CompactTextString(m) }
func (*ListPagePropsArrayObject) ProtoMessage()    {}
func (*ListPagePropsArrayObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{11}
}

func (m *ListPagePropsArrayObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPagePropsArrayObject.Unmarshal(m, b)
}
func (m *ListPagePropsArrayObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPagePropsArrayObject.Marshal(b, m, deterministic)
}
func (m *ListPagePropsArrayObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPagePropsArrayObject.Merge(m, src)
}
func (m *ListPagePropsArrayObject) XXX_Size() int {
	return xxx_messageInfo_ListPagePropsArrayObject.Size(m)
}
func (m *ListPagePropsArrayObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPagePropsArrayObject.DiscardUnknown(m)
}

var xxx_messageInfo_ListPagePropsArrayObject proto.InternalMessageInfo

func (m *ListPagePropsArrayObject) GetCelebImage() string {
	if m != nil {
		return m.CelebImage
	}
	return ""
}

func (m *ListPagePropsArrayObject) GetStyleImage() string {
	if m != nil {
		return m.StyleImage
	}
	return ""
}

func (m *ListPagePropsArrayObject) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *ListPagePropsArrayObject) GetMrp() int64 {
	if m != nil {
		return m.Mrp
	}
	return 0
}

func (m *ListPagePropsArrayObject) GetDiscountPrice() int64 {
	if m != nil {
		return m.DiscountPrice
	}
	return 0
}

type PdpCarousel struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Props                *PdpCarouselProps `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PdpCarousel) Reset()         { *m = PdpCarousel{} }
func (m *PdpCarousel) String() string { return proto.CompactTextString(m) }
func (*PdpCarousel) ProtoMessage()    {}
func (*PdpCarousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{12}
}

func (m *PdpCarousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PdpCarousel.Unmarshal(m, b)
}
func (m *PdpCarousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PdpCarousel.Marshal(b, m, deterministic)
}
func (m *PdpCarousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PdpCarousel.Merge(m, src)
}
func (m *PdpCarousel) XXX_Size() int {
	return xxx_messageInfo_PdpCarousel.Size(m)
}
func (m *PdpCarousel) XXX_DiscardUnknown() {
	xxx_messageInfo_PdpCarousel.DiscardUnknown(m)
}

var xxx_messageInfo_PdpCarousel proto.InternalMessageInfo

func (m *PdpCarousel) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PdpCarousel) GetProps() *PdpCarouselProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type PdpCarouselProps struct {
	Title                string                    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	PdpList              []*PdpCarouselArrayObject `protobuf:"bytes,2,rep,name=pdpList,proto3" json:"pdpList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PdpCarouselProps) Reset()         { *m = PdpCarouselProps{} }
func (m *PdpCarouselProps) String() string { return proto.CompactTextString(m) }
func (*PdpCarouselProps) ProtoMessage()    {}
func (*PdpCarouselProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{13}
}

func (m *PdpCarouselProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PdpCarouselProps.Unmarshal(m, b)
}
func (m *PdpCarouselProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PdpCarouselProps.Marshal(b, m, deterministic)
}
func (m *PdpCarouselProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PdpCarouselProps.Merge(m, src)
}
func (m *PdpCarouselProps) XXX_Size() int {
	return xxx_messageInfo_PdpCarouselProps.Size(m)
}
func (m *PdpCarouselProps) XXX_DiscardUnknown() {
	xxx_messageInfo_PdpCarouselProps.DiscardUnknown(m)
}

var xxx_messageInfo_PdpCarouselProps proto.InternalMessageInfo

func (m *PdpCarouselProps) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PdpCarouselProps) GetPdpList() []*PdpCarouselArrayObject {
	if m != nil {
		return m.PdpList
	}
	return nil
}

type PdpCarouselArrayObject struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ArticleType          string   `protobuf:"bytes,2,opt,name=article_type,json=articleType,proto3" json:"article_type,omitempty"`
	Mrp                  string   `protobuf:"bytes,3,opt,name=mrp,proto3" json:"mrp,omitempty"`
	DiscountPrice        string   `protobuf:"bytes,4,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PdpCarouselArrayObject) Reset()         { *m = PdpCarouselArrayObject{} }
func (m *PdpCarouselArrayObject) String() string { return proto.CompactTextString(m) }
func (*PdpCarouselArrayObject) ProtoMessage()    {}
func (*PdpCarouselArrayObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{14}
}

func (m *PdpCarouselArrayObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PdpCarouselArrayObject.Unmarshal(m, b)
}
func (m *PdpCarouselArrayObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PdpCarouselArrayObject.Marshal(b, m, deterministic)
}
func (m *PdpCarouselArrayObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PdpCarouselArrayObject.Merge(m, src)
}
func (m *PdpCarouselArrayObject) XXX_Size() int {
	return xxx_messageInfo_PdpCarouselArrayObject.Size(m)
}
func (m *PdpCarouselArrayObject) XXX_DiscardUnknown() {
	xxx_messageInfo_PdpCarouselArrayObject.DiscardUnknown(m)
}

var xxx_messageInfo_PdpCarouselArrayObject proto.InternalMessageInfo

func (m *PdpCarouselArrayObject) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PdpCarouselArrayObject) GetArticleType() string {
	if m != nil {
		return m.ArticleType
	}
	return ""
}

func (m *PdpCarouselArrayObject) GetMrp() string {
	if m != nil {
		return m.Mrp
	}
	return ""
}

func (m *PdpCarouselArrayObject) GetDiscountPrice() string {
	if m != nil {
		return m.DiscountPrice
	}
	return ""
}

type LandingPageGrid struct {
	Type                 string                `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Props                *LandingPageGridProps `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LandingPageGrid) Reset()         { *m = LandingPageGrid{} }
func (m *LandingPageGrid) String() string { return proto.CompactTextString(m) }
func (*LandingPageGrid) ProtoMessage()    {}
func (*LandingPageGrid) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{15}
}

func (m *LandingPageGrid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LandingPageGrid.Unmarshal(m, b)
}
func (m *LandingPageGrid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LandingPageGrid.Marshal(b, m, deterministic)
}
func (m *LandingPageGrid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LandingPageGrid.Merge(m, src)
}
func (m *LandingPageGrid) XXX_Size() int {
	return xxx_messageInfo_LandingPageGrid.Size(m)
}
func (m *LandingPageGrid) XXX_DiscardUnknown() {
	xxx_messageInfo_LandingPageGrid.DiscardUnknown(m)
}

var xxx_messageInfo_LandingPageGrid proto.InternalMessageInfo

func (m *LandingPageGrid) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LandingPageGrid) GetProps() *LandingPageGridProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type LandingPageGridProps struct {
	Title                string                        `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	GridArray            []*LandingPageGridArrayObject `protobuf:"bytes,2,rep,name=gridArray,proto3" json:"gridArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *LandingPageGridProps) Reset()         { *m = LandingPageGridProps{} }
func (m *LandingPageGridProps) String() string { return proto.CompactTextString(m) }
func (*LandingPageGridProps) ProtoMessage()    {}
func (*LandingPageGridProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{16}
}

func (m *LandingPageGridProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LandingPageGridProps.Unmarshal(m, b)
}
func (m *LandingPageGridProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LandingPageGridProps.Marshal(b, m, deterministic)
}
func (m *LandingPageGridProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LandingPageGridProps.Merge(m, src)
}
func (m *LandingPageGridProps) XXX_Size() int {
	return xxx_messageInfo_LandingPageGridProps.Size(m)
}
func (m *LandingPageGridProps) XXX_DiscardUnknown() {
	xxx_messageInfo_LandingPageGridProps.DiscardUnknown(m)
}

var xxx_messageInfo_LandingPageGridProps proto.InternalMessageInfo

func (m *LandingPageGridProps) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *LandingPageGridProps) GetGridArray() []*LandingPageGridArrayObject {
	if m != nil {
		return m.GridArray
	}
	return nil
}

type LandingPageGridArrayObject struct {
	Footer               string   `protobuf:"bytes,1,opt,name=footer,proto3" json:"footer,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ShopLandingPage      string   `protobuf:"bytes,3,opt,name=shop_landing_page,json=shopLandingPage,proto3" json:"shop_landing_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LandingPageGridArrayObject) Reset()         { *m = LandingPageGridArrayObject{} }
func (m *LandingPageGridArrayObject) String() string { return proto.CompactTextString(m) }
func (*LandingPageGridArrayObject) ProtoMessage()    {}
func (*LandingPageGridArrayObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{17}
}

func (m *LandingPageGridArrayObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LandingPageGridArrayObject.Unmarshal(m, b)
}
func (m *LandingPageGridArrayObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LandingPageGridArrayObject.Marshal(b, m, deterministic)
}
func (m *LandingPageGridArrayObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LandingPageGridArrayObject.Merge(m, src)
}
func (m *LandingPageGridArrayObject) XXX_Size() int {
	return xxx_messageInfo_LandingPageGridArrayObject.Size(m)
}
func (m *LandingPageGridArrayObject) XXX_DiscardUnknown() {
	xxx_messageInfo_LandingPageGridArrayObject.DiscardUnknown(m)
}

var xxx_messageInfo_LandingPageGridArrayObject proto.InternalMessageInfo

func (m *LandingPageGridArrayObject) GetFooter() string {
	if m != nil {
		return m.Footer
	}
	return ""
}

func (m *LandingPageGridArrayObject) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *LandingPageGridArrayObject) GetShopLandingPage() string {
	if m != nil {
		return m.ShopLandingPage
	}
	return ""
}

type FeedResponse struct {
	VideoList            *VideoList       `protobuf:"bytes,1,opt,name=video_list,json=VIDEO_LIST,proto3" json:"video_list,omitempty"`
	LandingPageGrid      *LandingPageGrid `protobuf:"bytes,2,opt,name=landing_page_grid,json=LANDING_PAGE_GRID,proto3" json:"landing_page_grid,omitempty"`
	PdpCarousel          *PdpCarousel     `protobuf:"bytes,3,opt,name=pdp_carousel,json=PDP_CAROUSEL,proto3" json:"pdp_carousel,omitempty"`
	ShopList             *ShopList        `protobuf:"bytes,4,opt,name=shop_list,json=SHOP_LIST,proto3" json:"shop_list,omitempty"`
	TagCard              *Tags            `protobuf:"bytes,5,opt,name=tag_card,json=TAGS,proto3" json:"tag_card,omitempty"`
	ListPage             *ListPage        `protobuf:"bytes,6,opt,name=list_page,json=LIST_PAGE,proto3" json:"list_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FeedResponse) Reset()         { *m = FeedResponse{} }
func (m *FeedResponse) String() string { return proto.CompactTextString(m) }
func (*FeedResponse) ProtoMessage()    {}
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{18}
}

func (m *FeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResponse.Unmarshal(m, b)
}
func (m *FeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResponse.Marshal(b, m, deterministic)
}
func (m *FeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResponse.Merge(m, src)
}
func (m *FeedResponse) XXX_Size() int {
	return xxx_messageInfo_FeedResponse.Size(m)
}
func (m *FeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResponse proto.InternalMessageInfo

func (m *FeedResponse) GetVideoList() *VideoList {
	if m != nil {
		return m.VideoList
	}
	return nil
}

func (m *FeedResponse) GetLandingPageGrid() *LandingPageGrid {
	if m != nil {
		return m.LandingPageGrid
	}
	return nil
}

func (m *FeedResponse) GetPdpCarousel() *PdpCarousel {
	if m != nil {
		return m.PdpCarousel
	}
	return nil
}

func (m *FeedResponse) GetShopList() *ShopList {
	if m != nil {
		return m.ShopList
	}
	return nil
}

func (m *FeedResponse) GetTagCard() *Tags {
	if m != nil {
		return m.TagCard
	}
	return nil
}

func (m *FeedResponse) GetListPage() *ListPage {
	if m != nil {
		return m.ListPage
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{19}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type GetShopDataRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopDataRequest) Reset()         { *m = GetShopDataRequest{} }
func (m *GetShopDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopDataRequest) ProtoMessage()    {}
func (*GetShopDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{20}
}

func (m *GetShopDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopDataRequest.Unmarshal(m, b)
}
func (m *GetShopDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopDataRequest.Marshal(b, m, deterministic)
}
func (m *GetShopDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopDataRequest.Merge(m, src)
}
func (m *GetShopDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopDataRequest.Size(m)
}
func (m *GetShopDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopDataRequest proto.InternalMessageInfo

func (m *GetShopDataRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetShopByVideoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopByVideoRequest) Reset()         { *m = GetShopByVideoRequest{} }
func (m *GetShopByVideoRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopByVideoRequest) ProtoMessage()    {}
func (*GetShopByVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{21}
}

func (m *GetShopByVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopByVideoRequest.Unmarshal(m, b)
}
func (m *GetShopByVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopByVideoRequest.Marshal(b, m, deterministic)
}
func (m *GetShopByVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopByVideoRequest.Merge(m, src)
}
func (m *GetShopByVideoRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopByVideoRequest.Size(m)
}
func (m *GetShopByVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopByVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopByVideoRequest proto.InternalMessageInfo

func (m *GetShopByVideoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetListPageDataRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListPageDataRequest) Reset()         { *m = GetListPageDataRequest{} }
func (m *GetListPageDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetListPageDataRequest) ProtoMessage()    {}
func (*GetListPageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{22}
}

func (m *GetListPageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListPageDataRequest.Unmarshal(m, b)
}
func (m *GetListPageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListPageDataRequest.Marshal(b, m, deterministic)
}
func (m *GetListPageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListPageDataRequest.Merge(m, src)
}
func (m *GetListPageDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetListPageDataRequest.Size(m)
}
func (m *GetListPageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListPageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListPageDataRequest proto.InternalMessageInfo

func (m *GetListPageDataRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetListPageDataRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Tag)(nil), "feed.Tag")
	proto.RegisterType((*Tags)(nil), "feed.Tags")
	proto.RegisterType((*TagsCardProps)(nil), "feed.TagsCardProps")
	proto.RegisterType((*VideoList)(nil), "feed.VideoList")
	proto.RegisterType((*VideoListProps)(nil), "feed.VideoListProps")
	proto.RegisterType((*VideoListPropsArrayObject)(nil), "feed.VideoListPropsArrayObject")
	proto.RegisterType((*ShopList)(nil), "feed.ShopList")
	proto.RegisterType((*ShopListProps)(nil), "feed.ShopListProps")
	proto.RegisterType((*ShopListPropsArrayObject)(nil), "feed.shopListPropsArrayObject")
	proto.RegisterType((*ListPage)(nil), "feed.ListPage")
	proto.RegisterType((*ListPageProps)(nil), "feed.ListPageProps")
	proto.RegisterType((*ListPagePropsArrayObject)(nil), "feed.ListPagePropsArrayObject")
	proto.RegisterType((*PdpCarousel)(nil), "feed.PdpCarousel")
	proto.RegisterType((*PdpCarouselProps)(nil), "feed.PdpCarouselProps")
	proto.RegisterType((*PdpCarouselArrayObject)(nil), "feed.PdpCarouselArrayObject")
	proto.RegisterType((*LandingPageGrid)(nil), "feed.LandingPageGrid")
	proto.RegisterType((*LandingPageGridProps)(nil), "feed.LandingPageGridProps")
	proto.RegisterType((*LandingPageGridArrayObject)(nil), "feed.LandingPageGridArrayObject")
	proto.RegisterType((*FeedResponse)(nil), "feed.FeedResponse")
	proto.RegisterType((*Request)(nil), "feed.Request")
	proto.RegisterType((*GetShopDataRequest)(nil), "feed.GetShopDataRequest")
	proto.RegisterType((*GetShopByVideoRequest)(nil), "feed.GetShopByVideoRequest")
	proto.RegisterType((*GetListPageDataRequest)(nil), "feed.GetListPageDataRequest")
}

func init() { proto.RegisterFile("feed.proto", fileDescriptor_d7a672c1337cb5ac) }

var fileDescriptor_d7a672c1337cb5ac = []byte{
	// 1099 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0x95, 0x4b, 0x2f, 0x3e, 0xe9, 0x65, 0x33, 0xbd, 0x6c, 0x9a, 0x76, 0x69, 0xb1, 0x84,
	0x28, 0xab, 0xd5, 0x06, 0x82, 0x40, 0x42, 0xe2, 0x16, 0xda, 0x12, 0xa2, 0x0d, 0x9b, 0xc8, 0x09,
	0x0b, 0x4f, 0x98, 0x69, 0x3c, 0x6b, 0x4c, 0x5c, 0xdb, 0xd8, 0x93, 0x48, 0x51, 0xd5, 0x17, 0x1e,
	0x79, 0xe5, 0x11, 0x89, 0x0f, 0xc1, 0x2b, 0x1f, 0x63, 0xbf, 0x02, 0x1f, 0x04, 0xcd, 0x99, 0x71,
	0xea, 0x69, 0x6d, 0xb1, 0x0f, 0xfb, 0x36, 0x73, 0x2e, 0xff, 0x39, 0xe7, 0x37, 0x27, 0x13, 0x03,
	0xbc, 0x64, 0xcc, 0x79, 0x1a, 0xc5, 0x21, 0x0f, 0x49, 0x55, 0xac, 0x9b, 0x47, 0x6e, 0x18, 0xba,
	0x3e, 0x6b, 0xd1, 0xc8, 0x6b, 0xd1, 0x20, 0x08, 0x39, 0xe5, 0x5e, 0x18, 0x24, 0x32, 0xc6, 0xfc,
	0x04, 0x2a, 0x63, 0xea, 0x92, 0x87, 0xb0, 0xc6, 0xa9, 0x6b, 0x4f, 0xd9, 0xa2, 0x51, 0x3a, 0x29,
	0x9d, 0x1a, 0xd6, 0x2a, 0xa7, 0xee, 0x33, 0xb6, 0x20, 0x07, 0xb0, 0x2e, 0x1c, 0xbe, 0x17, 0x4c,
	0x1b, 0x65, 0xf4, 0x88, 0xc0, 0xbe, 0x17, 0x4c, 0xcd, 0x0b, 0xa8, 0x8e, 0xa9, 0x9b, 0x10, 0x02,
	0x55, 0xbe, 0x88, 0x98, 0x4a, 0xc4, 0x35, 0x79, 0x0f, 0x56, 0xa2, 0x38, 0x8c, 0x12, 0xcc, 0xa9,
	0xb5, 0x77, 0x9e, 0x62, 0x59, 0x22, 0xfc, 0x8c, 0xc6, 0xce, 0x50, 0xb8, 0x2c, 0x19, 0x61, 0x0e,
	0x60, 0x53, 0xb3, 0x93, 0x5d, 0x58, 0xe1, 0x1e, 0xf7, 0x53, 0x41, 0xb9, 0x21, 0xa7, 0x00, 0x9c,
	0xba, 0x89, 0x4d, 0xe3, 0x98, 0x2e, 0x1a, 0xe5, 0x93, 0xca, 0x69, 0xad, 0x6d, 0x2c, 0x65, 0x2d,
	0x43, 0x38, 0x3b, 0xc2, 0x67, 0x3e, 0x03, 0xe3, 0x85, 0xe7, 0xb0, 0xb0, 0xef, 0x25, 0x3c, 0xb7,
	0xb8, 0xc7, 0x7a, 0x71, 0xbb, 0x52, 0x65, 0x99, 0xa3, 0x55, 0xf7, 0x57, 0x09, 0xb6, 0x74, 0x4f,
	0x41, 0x7d, 0x47, 0x60, 0x50, 0xdf, 0x73, 0x83, 0x2b, 0x16, 0x70, 0x45, 0xea, 0xd6, 0x20, 0xf8,
	0x26, 0x8c, 0xd9, 0xd4, 0xf7, 0x1b, 0x15, 0xc9, 0x37, 0x61, 0xac, 0xe3, 0xfb, 0xe4, 0x0b, 0x80,
	0xb9, 0x90, 0xc7, 0xd2, 0x1b, 0x55, 0x6c, 0xeb, 0x38, 0xaf, 0x20, 0x0c, 0x18, 0x5c, 0xfe, 0xc2,
	0x26, 0xdc, 0xca, 0xa4, 0x98, 0x73, 0x38, 0x28, 0x0c, 0x24, 0x8f, 0x94, 0xba, 0xbc, 0x3f, 0x59,
	0xaf, 0x31, 0x97, 0xe1, 0xc1, 0x94, 0x3c, 0x82, 0xaa, 0xc0, 0x76, 0x9f, 0x26, 0x9a, 0xc9, 0x21,
	0x18, 0xc9, 0xcf, 0x61, 0x64, 0xfb, 0x61, 0x38, 0x55, 0x65, 0xaf, 0x0b, 0x43, 0x3f, 0x0c, 0xa7,
	0x66, 0x0f, 0xd6, 0x47, 0x62, 0x5d, 0x04, 0x39, 0x7f, 0x02, 0xd2, 0x14, 0x8d, 0xf1, 0x9f, 0x25,
	0xd8, 0xd4, 0x1c, 0x6f, 0x16, 0xf1, 0x67, 0x00, 0xd8, 0x06, 0xcd, 0x20, 0x7e, 0x4b, 0x96, 0x93,
	0x64, 0x4f, 0xcd, 0x12, 0xc6, 0xc6, 0x25, 0xe0, 0x09, 0x34, 0x8a, 0xc2, 0x44, 0x9d, 0xde, 0x15,
	0x75, 0x97, 0x75, 0xe2, 0x06, 0xb9, 0xcd, 0x2e, 0x6d, 0xd9, 0x41, 0x59, 0x71, 0x9b, 0x5d, 0x8e,
	0xb1, 0x89, 0x5d, 0x58, 0x99, 0x84, 0xb3, 0x80, 0x63, 0x91, 0x15, 0x4b, 0x6e, 0x04, 0x4d, 0x3c,
	0x40, 0xa4, 0xbf, 0x3e, 0xcd, 0x34, 0x45, 0xa3, 0xf9, 0x2d, 0x6c, 0x6a, 0x76, 0xf2, 0x29, 0x18,
	0xbe, 0x97, 0x70, 0x39, 0x61, 0xa5, 0x6c, 0xfb, 0x5a, 0x9c, 0xd6, 0xfe, 0x32, 0xc1, 0xfc, 0xbb,
	0x04, 0x8d, 0xa2, 0x38, 0x72, 0x0c, 0xb5, 0x09, 0xf3, 0xd9, 0xa5, 0x9d, 0xa5, 0x00, 0x68, 0xea,
	0x21, 0x8a, 0x63, 0xa8, 0x25, 0x7c, 0xe1, 0x33, 0x15, 0x20, 0x61, 0x00, 0x9a, 0x7a, 0xf7, 0x59,
	0x55, 0xee, 0xb0, 0x7a, 0x00, 0x95, 0xab, 0x38, 0x6a, 0x54, 0x91, 0x94, 0x58, 0x92, 0x77, 0x60,
	0xcb, 0xf1, 0x12, 0x64, 0x66, 0x47, 0xb1, 0x37, 0x61, 0x8d, 0x15, 0x74, 0x6e, 0xa6, 0xd6, 0xa1,
	0x30, 0x9a, 0x03, 0xa8, 0x0d, 0x9d, 0xe8, 0x8c, 0xc6, 0xe1, 0x2c, 0x61, 0x7e, 0x2e, 0xd1, 0x27,
	0x3a, 0xd1, 0x7d, 0x49, 0x24, 0x93, 0xa5, 0x41, 0xfd, 0x09, 0x1e, 0xdc, 0x75, 0x15, 0x0c, 0xe9,
	0xc7, 0xb0, 0x16, 0x39, 0x38, 0x2d, 0xea, 0x67, 0x75, 0x74, 0x4f, 0x39, 0x4b, 0x3a, 0x0d, 0x36,
	0x7f, 0x2f, 0xc1, 0x7e, 0x7e, 0x4c, 0xc1, 0x94, 0xbd, 0x0d, 0x1b, 0x34, 0xe6, 0xde, 0xc4, 0x67,
	0x36, 0x36, 0x27, 0xd9, 0xd6, 0x94, 0x6d, 0x2c, 0x7a, 0x54, 0xfc, 0x24, 0xd6, 0x02, 0x7e, 0x55,
	0x74, 0xde, 0xe1, 0xf7, 0x3d, 0x6c, 0xf7, 0x69, 0xe0, 0x78, 0x81, 0x2b, 0xae, 0xbd, 0x1b, 0x7b,
	0x4e, 0x2e, 0xc3, 0xf7, 0x75, 0x86, 0x4d, 0x35, 0x55, 0x7a, 0xa6, 0xc6, 0xd1, 0x87, 0xdd, 0x3c,
	0x77, 0x01, 0xcb, 0xcf, 0xc1, 0x70, 0x63, 0xcf, 0xe9, 0x64, 0x9e, 0xfc, 0x93, 0xdc, 0x33, 0xb4,
	0xd9, 0x5d, 0xa6, 0x98, 0x73, 0x68, 0x16, 0x07, 0x92, 0x7d, 0x58, 0x7d, 0x19, 0x86, 0x9c, 0xc5,
	0xe9, 0x5f, 0x9e, 0xdc, 0xdd, 0xe2, 0x2e, 0x67, 0x71, 0x3f, 0x86, 0xba, 0x7c, 0x0c, 0xa5, 0xa0,
	0x1d, 0x89, 0x08, 0x49, 0x76, 0x1b, 0xdf, 0x87, 0xdb, 0x83, 0xcc, 0x7f, 0xca, 0xb0, 0xf1, 0x35,
	0x63, 0x8e, 0xc5, 0x92, 0x28, 0x0c, 0x12, 0x46, 0x5a, 0xb7, 0xef, 0x70, 0xc2, 0xf1, 0xb8, 0x5a,
	0x7b, 0xfb, 0xce, 0x2b, 0x6f, 0xc1, 0x8b, 0xde, 0xf9, 0xc5, 0xc0, 0xee, 0xf7, 0x46, 0x63, 0x72,
	0x06, 0xf5, 0xec, 0x41, 0xb6, 0xe8, 0x49, 0x51, 0xde, 0xcb, 0x25, 0x60, 0xd5, 0xfb, 0x9d, 0xe7,
	0xe7, 0xbd, 0xe7, 0x5d, 0x7b, 0xd8, 0xe9, 0x5e, 0xd8, 0x5d, 0xab, 0x77, 0x4e, 0x3e, 0x82, 0x8d,
	0xc8, 0x89, 0xec, 0x89, 0x1a, 0x29, 0xac, 0xb6, 0xd6, 0xae, 0xdf, 0x9b, 0x47, 0x6b, 0x63, 0x78,
	0x3e, 0xb4, 0xcf, 0x3a, 0xd6, 0xe0, 0xbb, 0xd1, 0x45, 0x9f, 0x3c, 0x49, 0x9f, 0x7d, 0x51, 0x6b,
	0x15, 0x73, 0xb6, 0xf4, 0xd7, 0xdb, 0x32, 0x46, 0xdf, 0x0c, 0x86, 0xb2, 0x52, 0x53, 0x7e, 0x20,
	0x4c, 0x68, 0xec, 0xe0, 0x6f, 0xb1, 0xd6, 0x86, 0xdb, 0x3f, 0x7b, 0xab, 0x3a, 0xee, 0x74, 0x47,
	0x42, 0x51, 0x88, 0x49, 0x66, 0xab, 0x59, 0xc5, 0xf4, 0x65, 0xb1, 0x0c, 0x21, 0x86, 0xb5, 0x9b,
	0x06, 0xac, 0x59, 0xec, 0xd7, 0x19, 0x4b, 0xb8, 0x79, 0x0a, 0xa4, 0xcb, 0xb8, 0x38, 0xf6, 0x9c,
	0x72, 0xaa, 0xac, 0x79, 0xa3, 0x68, 0xbe, 0x0b, 0x7b, 0x2a, 0xf2, 0xab, 0x05, 0x22, 0x4d, 0x83,
	0xb7, 0xa0, 0xec, 0x39, 0x2a, 0xb4, 0xec, 0x39, 0xe6, 0x97, 0xb0, 0xdf, 0x65, 0x3c, 0x3d, 0xf7,
	0x7f, 0x64, 0x85, 0x2d, 0xa0, 0x57, 0xe9, 0x28, 0xe0, 0xba, 0xfd, 0xaa, 0x02, 0x35, 0x71, 0xbb,
	0x23, 0x16, 0xcf, 0xbd, 0x09, 0x23, 0x23, 0x2c, 0x32, 0x73, 0x1f, 0x42, 0x94, 0x6c, 0xca, 0x06,
	0x95, 0x78, 0x93, 0xc8, 0x6d, 0x76, 0x2a, 0xcc, 0xe6, 0x6f, 0xaf, 0xfe, 0xfd, 0xa3, 0xbc, 0x4b,
	0x48, 0x6b, 0xfe, 0x41, 0x8b, 0x87, 0x51, 0x40, 0xe7, 0x2d, 0x75, 0xeb, 0xe4, 0x07, 0xd8, 0x56,
	0xfd, 0x2c, 0x15, 0x1b, 0x52, 0xe2, 0x3e, 0x90, 0x5c, 0xf1, 0x87, 0x28, 0x5e, 0x27, 0xdb, 0x42,
	0x5c, 0xdc, 0x67, 0xeb, 0x5a, 0x74, 0x74, 0x43, 0x5c, 0x54, 0xce, 0x02, 0x20, 0x47, 0x4b, 0xe5,
	0x1c, 0x2e, 0xb9, 0xea, 0x26, 0xaa, 0x1f, 0x91, 0xa6, 0x50, 0xf7, 0x55, 0x92, 0x3a, 0xa1, 0x75,
	0x2d, 0x30, 0xdd, 0x90, 0x3e, 0x6c, 0x74, 0x19, 0xef, 0xf8, 0x3e, 0xde, 0x47, 0xf2, 0x3a, 0x44,
	0x0e, 0x50, 0x76, 0x87, 0xd4, 0x85, 0x6c, 0x14, 0x46, 0x33, 0x9f, 0xc6, 0x2a, 0xfb, 0x47, 0xd8,
	0xd2, 0x2f, 0x98, 0x1c, 0x6a, 0x3c, 0xf4, 0x6b, 0xcf, 0x55, 0x3f, 0x44, 0xf5, 0x3d, 0xb2, 0x93,
	0x22, 0x91, 0xd2, 0xad, 0x6b, 0xcf, 0xb9, 0xb9, 0x5c, 0xc5, 0xef, 0xe1, 0x0f, 0xff, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x95, 0xe6, 0x26, 0x84, 0x41, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedServiceClient is the client API for FeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedServiceClient interface {
	// mock data
	GetLandingPageData(ctx context.Context, in *Request, opts ...grpc.CallOption) (*FeedResponse, error)
	// done
	GetShopPageData(ctx context.Context, in *GetShopDataRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	GetListPageData(ctx context.Context, in *GetListPageDataRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	GetAllVideos(ctx context.Context, in *Request, opts ...grpc.CallOption) (*FeedResponse, error)
	GetShopByVideo(ctx context.Context, in *GetShopByVideoRequest, opts ...grpc.CallOption) (*FeedResponse, error)
}

type feedServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedServiceClient(cc *grpc.ClientConn) FeedServiceClient {
	return &feedServiceClient{cc}
}

func (c *feedServiceClient) GetLandingPageData(ctx context.Context, in *Request, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, "/feed.FeedService/GetLandingPageData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetShopPageData(ctx context.Context, in *GetShopDataRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, "/feed.FeedService/GetShopPageData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetListPageData(ctx context.Context, in *GetListPageDataRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, "/feed.FeedService/GetListPageData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetAllVideos(ctx context.Context, in *Request, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, "/feed.FeedService/GetAllVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetShopByVideo(ctx context.Context, in *GetShopByVideoRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, "/feed.FeedService/GetShopByVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServiceServer is the server API for FeedService service.
type FeedServiceServer interface {
	// mock data
	GetLandingPageData(context.Context, *Request) (*FeedResponse, error)
	// done
	GetShopPageData(context.Context, *GetShopDataRequest) (*FeedResponse, error)
	GetListPageData(context.Context, *GetListPageDataRequest) (*FeedResponse, error)
	GetAllVideos(context.Context, *Request) (*FeedResponse, error)
	GetShopByVideo(context.Context, *GetShopByVideoRequest) (*FeedResponse, error)
}

// UnimplementedFeedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFeedServiceServer struct {
}

func (*UnimplementedFeedServiceServer) GetLandingPageData(ctx context.Context, req *Request) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLandingPageData not implemented")
}
func (*UnimplementedFeedServiceServer) GetShopPageData(ctx context.Context, req *GetShopDataRequest) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopPageData not implemented")
}
func (*UnimplementedFeedServiceServer) GetListPageData(ctx context.Context, req *GetListPageDataRequest) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListPageData not implemented")
}
func (*UnimplementedFeedServiceServer) GetAllVideos(ctx context.Context, req *Request) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVideos not implemented")
}
func (*UnimplementedFeedServiceServer) GetShopByVideo(ctx context.Context, req *GetShopByVideoRequest) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopByVideo not implemented")
}

func RegisterFeedServiceServer(s *grpc.Server, srv FeedServiceServer) {
	s.RegisterService(&_FeedService_serviceDesc, srv)
}

func _FeedService_GetLandingPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetLandingPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.FeedService/GetLandingPageData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetLandingPageData(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetShopPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetShopPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.FeedService/GetShopPageData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetShopPageData(ctx, req.(*GetShopDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetListPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetListPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.FeedService/GetListPageData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetListPageData(ctx, req.(*GetListPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetAllVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetAllVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.FeedService/GetAllVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetAllVideos(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetShopByVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopByVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetShopByVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.FeedService/GetShopByVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetShopByVideo(ctx, req.(*GetShopByVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feed.FeedService",
	HandlerType: (*FeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLandingPageData",
			Handler:    _FeedService_GetLandingPageData_Handler,
		},
		{
			MethodName: "GetShopPageData",
			Handler:    _FeedService_GetShopPageData_Handler,
		},
		{
			MethodName: "GetListPageData",
			Handler:    _FeedService_GetListPageData_Handler,
		},
		{
			MethodName: "GetAllVideos",
			Handler:    _FeedService_GetAllVideos_Handler,
		},
		{
			MethodName: "GetShopByVideo",
			Handler:    _FeedService_GetShopByVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feed.proto",
}
